### ISSUE TITLE
Hidden theme?

### ISSUE THREAD

**Issue by acnleditor2** [ErmanSayin/Themely#102]
I just saw that there is a hidden theme, surely it has to do with the closed code
It's My Melody 40th Anniversary,
You should have no theme to install this.
Steps:
Dump the current theme
Install it. And it is already

**Comment by ErmanSayin** [comment]
Not a hidden theme -- it's the latest theme you had installed before switching back to the default theme. When you switch to a default theme, the system doesn't wipe out the theme cache, which is what Themely dumps.
