### ISSUE TITLE
[Suggestion] Romanian Translation

### ISSUE THREAD

**Issue by adrot** [ErmanSayin/Themely#107]
I already worked on a few localization projects in the past, and I would like to lend a hand to the app's localization if you like.

**Comment by ErmanSayin** [comment]
Hello, can you translate the strings in this file, please? Please email the translation to support@3dsthem.es
Thank you
https://github.com/ErmanSayin/Themely/blob/master/strings.cpp

**Comment by adrot** [comment]
Alright, should be done by now. Two questions.  On the strings "err_fail_open" and "err_fail_read", are they referring to a file in particular? The other question, can I place Romanian diacritics on the translation (ă,â,î,ț,ș)?

**Comment by ErmanSayin** [comment]
Yes, the %s part is the filename. And yes, placing diacritics should work
