### ISSUE TITLE
(Suggestion) Support for downloading from Theme Plaza

### ISSUE THREAD

**Issue by jupitteer** [ErmanSayin/Themely#112]
A lot of themes recently have become exclusive to that site. Browsing from both 3dsthem.es and theme plaza would be really nice.

**Comment by Elionna** [comment]
why? 3dsthem.es is better and has all the themes and activity, support for worse sites is pointless

**Comment by RinMaru** [comment]
Theme plaza actually has NSFW themes mostly lol

**Comment by Elionna** [comment]
Lmao is that what themeplaza is used for? I rest my case then, garbage site.

**Comment by ErmanSayin** [comment]
I might consider this if the site gets big enough 🤔

**Comment by corin12355** [comment]
What does "cooperate" involve exactly?

**Comment by ErmanSayin** [comment]
@corin12355 Having an API available

**Comment by corin12355** [comment]
Oh, sure, what content exactly do you need from the API?

**Comment by ErmanSayin** [comment]
@corin12355 Just make an API that supplies the following

- Total count of themes from the search OR number of pages
For each theme
- ID
- Title
- Description
- Author
- Boolean whether if the theme has a BGM or not

**Comment by corin12355** [comment]
@ErmanSayin I don't think any modern project would use XML in this day and age :P

Sounds good though, I'll see what I can do!

**Comment by Dimmidice** [comment]
So this isn't happening then? If so that's a shame.

**Comment by ErmanSayin** [comment]
Since the site admins have not cooperated, I'll have to close this.
