### ISSUE TITLE
Themely 1.4.0 not working

### ISSUE THREAD

**Issue by That1Guy20XX** [ErmanSayin/Themely#118]
I'm on 11.4 with Homebrew and no CFW using Themely v1.4.0, but I get a red screen when I start it. Did I do something wrong?

**Comment by sks316** [comment]
You could try redownloading Themely 1.4.0.
Which entrypoint are you using? Which system model?

**Comment by That1Guy20XX** [comment]
New 3DS, using Freakyhax.

**Comment by That1Guy20XX** [comment]
Even redownloading doesn't work.

**Comment by ErmanSayin** [comment]
Duplicate of #99. Make sure your payload is updated.

**Comment by That1Guy20XX** [comment]
Themely 1.4.0 still doesn't work. Updated payload with RPwnG or not. Even redownloading again won't work.
