### ISSUE TITLE
Move from sf2d to pp2d

### ISSUE THREAD

**Issue by ErmanSayin** [ErmanSayin/Themely#127]

**Comment by papermario69** [comment]
um, can I get in english please? I have no idea what that means.

**Comment by ErmanSayin** [comment]
@papermario69 these are both 2D graphics libraries, sf2d is deprecated

**Comment by papermario69** [comment]
Ok, how do I switch to pp2d?

**Comment by ErmanSayin** [comment]
@papermario69 This is something I have to do to the app myself
