### ISSUE TITLE
Looking at specific themes causes the "software closed" menu to pop up with no warning.

### ISSUE THREAD

**Issue by rupeescreamer** [ErmanSayin/Themely#13]
This keeps me from advancing further into the theme list, and only happens to specific themes. When I remove the themes that cause the program to close, another theme starts doing it.

**Comment by Robz8** [comment]
I posted the same thing on the GBATemp thread.

> I encountered a new bug. When selecting a 33rd theme by pressing down, the app throws me into the 3DS' shutdown screen.
Going past the 33rd theme by pressing right works, but pressing up/down, the app still throws me into the 3DS' shutdown screen.

**Comment by ErmanSayin** [comment]
Hello, is it possible for you send me all the themes in a ZIP file for me to debug? Thanks.

**Comment by rupeescreamer** [comment]
Sure, here's one that caused the . I don't think the theme itself makes a difference. For reference, this was the 24th theme on the list.
[Moonside.zip](https://github.com/ErmanSayin/Themely/files/965828/Moonside.zip)

**Comment by ErmanSayin** [comment]
@rupeescreamer Can I get your **whole** /Themes folder please?

**Comment by Robz8** [comment]
Have you tried copying and pasting the theme to get to 40?

**Comment by Robz8** [comment]
Now in version v1.1.2, instead crashing into the shutdown screen, it crashes into the 3DS HOME Menu with an error message saying that the system will restart.

I'll send you a .zip file containing the themes.

**Comment by Robz8** [comment]
Here you go!
https://www.odrive.com/s/0221a786-9ed7-4b33-8ebc-ab78b243dd10-590658e8
