### ISSUE TITLE
"Content-Disposition header not in response" error, cannot download anymore themes

### ISSUE THREAD

**Issue by Lagmobile** [ErmanSayin/Themely#130]
Was working absolutely fine before this error. Downloaded about 8 or 9 themes but now can't download anymore. Tried deleting some older themes before installation and some themes downloaded through themely. Still no luck.

**Comment by adramatech** [comment]
Same error here, just updated same error appears -before update no problem- still can installing previouly downloaded themes in app

**Comment by victorseibert** [comment]
The same too, version 1.4.1, i download just one theme and this appear to me

**Comment by ibrokemypie** [comment]
Same here, cant download any though

**Comment by ErmanSayin** [comment]
should be fixed.
