### ISSUE TITLE
should i get this

### ISSUE THREAD

**Issue by LennyMcLennington** [ErmanSayin/Themely#132]
someone said erman will steal my sensitive data of my 3ds if i download it because its closed source on the subreddit and some discord servers just wondering what its all about and if its safe

**Comment by ErmanSayin** [comment]
im not dumb enough to get my 3ds banned soo yea its safe

**Comment by LennyMcLennington** [comment]
how is that relevant though

**Comment by ErmanSayin** [comment]
what other sensitive data is there on a 3ds other than the seed file lol

**Comment by ZeroGravity83** [comment]
Hi I have a question. Like LennyMcLennington mentioned there's a bad rumor about you floating around in the community. Especially the subreddit is being a toxic s**thole and most people in there assume that Themely is a malware. Someone even went so far as to take the source code of Themely v1.3.1 and claims it as his own.
https://github.com/Favna/3DSThemeManager
Are you really ok with this? Also, are you not planning to do something to restore your reputation/clear our name? I understand you don't want to make Themely open source, but seriously it's getting out of hand and people are spreading a negative image of you.

**Comment by ErmanSayin** [comment]
The app got closed sourced because of the community in the first place so it's not getting opened because of it

**Comment by ZeroGravity83** [comment]
Yeah I'm not saying you should make Themely open source, but can you please try to do something to prove to people in the community that Themely is safe. Well I'm not trying to force you or anything but are you really ok with Favna taking your code and making it his own (They don't even give credit to you btw)
Also someone made another theme website(theme plaza) because of the drama.

**Comment by PlatinumLucario** [comment]
I'm kinda curious as to what the community said to ErmanSayin in which made him feel like making the project closed source. I fully understand his decision to do so, I'm not going to be negative about anything.

Also ZeroGravity83, Favna's fork of Themely (renamed as 3DSThemeManager) does actually say "Copyright (c) 2017 Erman SAYIN" at the bottom of the licence, which still credits him. So as long as ErmanSayin is okay with that fork of Themely being licenced under GNU GPL v3 (which was what Themely versions 1.3.0 and earlier used) and being used in that way.

**Comment by sks316** [comment]
Guys, Themely is safe. I use it frequently and it's actually quite good. However, it's up to you whether or not you'd like to use it.
