### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by Uyuiyu** [ErmanSayin/Themely#134]
File attached
[strings.zip](https://github.com/ErmanSayin/Themely/files/1257546/strings.zip)

**Comment by adrot** [comment]
You wrote a few strings wrong on the zip.
{"press_start",         L"Pulsa START para ssalit."}
{"update_prompt",       L"¿Instlar ésta actualización?"}
{"no_themes_1",         L"¡No se han encontrado teas!"}

**Comment by Uyuiyu** [comment]
Ups

**Comment by Uyuiyu** [comment]
[strings.zip](https://github.com/ErmanSayin/Themely/files/1261517/strings.zip)
Fixed
