### ISSUE TITLE
ERROR Content-Disposition header not in response

### ISSUE THREAD

**Issue by McJordan447** [ErmanSayin/Themely#136]
I've had Themely installed for quite a while on my O3DS and since Themely auto-updated to v1.4.1 i get this error every time i try to download a theme, both in the download section and in through QR download.

**Comment by Juanito9001** [comment]
same error here

**Comment by Forsburn** [comment]
Same issue as well. Got it at the same time the guy before me commented.

**Comment by ibrokemypie** [comment]
Not working at all on O3ds 11.4, not working on 1.3 themely with qr, nor 1.4.1 themely

**Comment by ErmanSayin** [comment]
duplicate
