### ISSUE TITLE
Crashes on boot please help

### ISSUE THREAD

**Issue by Hannahbananah** [ErmanSayin/Themely#143]
I'm on arms9 luma new 3ds 11.4.0 I download this theme with with a waterfall and it froze since then. I cant get to homescreen at all. Boots up black. Please help Btw I used Fbi to install and I removed the themes but still didn't work. Thanks for your time.

**Comment by ErmanSayin** [comment]
Delete this folder on your SD Card:
Nintendo 3DS/[ID0]/[ID1]/extdata/00000000/**000002cd**
**(000002cd for JPN, 000002cd for USA, 000002ce for EU)**
