### ISSUE TITLE
Make It Open Source!

### ISSUE THREAD

**Issue by GonderWin** [ErmanSayin/Themely#144]
I Wish :cry:

**Comment by ErmanSayin** [comment]
no

**Comment by psmirage** [comment]
@GonderWin Use Anemone3DS instead, it's better. It's open source and even supports splashes(QR code installation too).
The developer stronautlevel2 says he will eventually add themeplaza integration, which allows you to download themes/splashes straight from your system.
https://github.com/astronautlevel2/Anemone3DS/releases
