### ISSUE TITLE
Shutdown after showing Logo

### ISSUE THREAD

**Issue by Klauserus** [ErmanSayin/Themely#17]
Dear Programmer
At First, i start HBC. After that
I boot Themely Version 1.1.0. I see the Themely Logo a half second, after that my new 3ds XL shut down.

technical Infos:

New 3ds Xl wit Firmware 11.1.0.34
Themely official Version 1.1.0
Themes Unsziped on SD:/Themes/

When you need more informations, please ask.

Thanks

**Comment by ErmanSayin** [comment]
Try using the CIA version.
