### ISSUE TITLE
Multilinguality

### ISSUE THREAD

**Issue by ErmanSayin** [ErmanSayin/Themely#19]
Detect locale based on console language

**Comment by ErmanSayin** [comment]
seems like a waste of time after thinking about it further

**Comment by Kitrune** [comment]
If you need it, i can help with the spanish localization.

**Comment by ErmanSayin** [comment]
@Kitrune http://gbatemp.net/threads/release-themely-a-beautiful-theme-manager.468707/page-28#post-7338327
