### ISSUE TITLE
Exit sequence causes unexpected "software closed" screen

### ISSUE THREAD

**Issue by ImmortalScientist** [ErmanSayin/Themely#21]
Loving Themely so far, but I have noticed using v1.1.1, to exit the program, the home-button is non responsive, and when the "Start" button is pressed, the program exits to the shutdown screen with the message "software closed". Not sure if this intentional, so I thought I'd report :)

**Comment by CodyMKW** [comment]
I feel like that is intentional like after you install a theme press start it goes to the software closed screen then you press home and go to the home menu and the theme is changed

**Comment by ahoischen** [comment]
This is indeed a feature. Going to the software closed screen allows the home menu to correctly load the new theme. Allowing the home button while using the program might cause some weirdness so it's best to disallow that.

**Comment by ErmanSayin** [comment]
Yes, this is indeed intentional

**Comment by ImmortalScientist** [comment]
OK thanks for confirming that :D
