### ISSUE TITLE
BGM preview is buggy

### ISSUE THREAD

**Issue by zweilous** [ErmanSayin/Themely#25]
there's no problem when using the theme itself but the way the app plays the music has a problem affecting the sound quality. it doesn't affect all of them; just a few

[sample bgm.zip](https://github.com/ErmanSayin/Themely/files/966740/sample.bgm.zip)
[sample bgm 2.zip](https://github.com/ErmanSayin/Themely/files/966741/sample.bgm.2.zip)

**Comment by ErmanSayin** [comment]
This is most likely fixed in v1.4.0 with the addition of the BCSTM player.
