### ISSUE TITLE
Program becomes suspended

### ISSUE THREAD

**Issue by sks316** [ErmanSayin/Themely#26]
If I press the HOME Button, install a theme, and press Start, instead of the Shutdown Screen, Themely gets suspended. Resuming it takes me to a screen that just says "by Erman"

**Comment by ErmanSayin** [comment]
hmm I need to be able to use `aptMainLoop` whilst having the home menu disabled

**Comment by sks316** [comment]
Thing is, this didn't happen in version 1.1.0 or 1.1.1.
