### ISSUE TITLE
3dsx won't open on 11.4

### ISSUE THREAD

**Issue by chandlerperson2** [ErmanSayin/Themely#29]
you lied to us! 11.4 doesn`t work on 3dsx!

**Comment by ErmanSayin** [comment]
Update your payload dude.

**Comment by chandlerperson2** [comment]
otherapp or ropbin

**Comment by ErmanSayin** [comment]
otherapp

**Comment by chandlerperson2** [comment]
It Worked! thanks........ but my 3ds broke... just now.... wont turn on....

**Comment by Clement95** [comment]
Your probleme isn't resolved ? Your 3DS wont turn on ever ?

**Comment by chandlerperson2** [comment]
no

**Comment by AnalogMan151** [comment]
Also having this issue on 11.5U, payload is all updated but this 3DSX and only this one locks up on a red bottom screen. Tried latest release and release before that to no avail.
