### ISSUE TITLE
Theme downloader

### ISSUE THREAD

**Issue by Jan200101** [ErmanSayin/Themely#3]
a Online Theme Browser would give Themely a great advantage over Howlin and could be implemented using 3dsthem.es

**Comment by ErmanSayin** [comment]
This is a planned feature.

**Comment by Jan200101** [comment]
Closing as its already planned 
![image](https://cloud.githubusercontent.com/assets/15076013/25399269/315546e0-29ef-11e7-94e9-22e6c6645163.png)

**Comment by ahoischen** [comment]
I'd suggest keeping this issue open until it is implemented to reduce duplicates and make it easier for potential contributors to centralise this feature's discussion.

Aside from that, I'd like to note for the uninformed that [3dsthem.es](https://3dsthem.es/) was created by this project's author and is, therefore, a perfect choice for online integration into this app. It is also the biggest theme hosting site (source: 3dsthem.es).

**Comment by ErmanSayin** [comment]
@ahoischen I agree.

**Comment by Pirater12** [comment]
@ErmanSayin This might help:- https://github.com/devkitPro/3ds-examples/blob/master/network/sslc/source/ssl.c

**Comment by ErmanSayin** [comment]
@Pirater12 I already have the networking code ready

**Comment by ErmanSayin** [comment]
IDEA: allow for installation of theme without having them on the themes list

**Comment by ErmanSayin** [comment]
Done! Will be available in v1.4.0.
