### ISSUE TITLE
couple of bugs with BGM

### ISSUE THREAD

**Issue by BandarFHD** [ErmanSayin/Themely#32]
So, I installed a theme and while previewing the BGM of the theme it was playing very fast. What I mean is the BGM is playing x2 the speed. And after installing the theme it was perfect with no problems but after an hour or two of playing and returning to the home menu there was an annoying beeping noise alongside the BGM. So I went back to Themely and re-installed the theme and the beeping noise is gone. So I guess the theme itself is perfect and the issue is from the app. 
My device is New 3ds XL and running on 11.3
I have 466 themes already on the device.
If you need any more info feel free to ask.

**Comment by ErmanSayin** [comment]
#25
