### ISSUE TITLE
[Suggestion] Changing selected theme in fullscreen preview mode.

### ISSUE THREAD

**Issue by techmouse** [ErmanSayin/Themely#39]
## Problem: 
If the user wanted to select themes based on its fullscreen preview, then they would have to enter fullscreen preview mode, view it, exit fullscreen preview mode, move down to the next theme, and repeat. This could be quite grueling if a person has 50+ themes.

## Suggestion:
Allow users to switch selected themes while in fullscreen preview mode.

## More Suggestion:
It would also be great if the user could still preform all of the same functions in fullscreen preview mode, as they could if they were not.

If this presents an interface issue (because it could conflict with the preview), then when the user presses a button the first time, a message could come up that says `Press {button name} Again To {action}`. The action is cancelled and the message will disappear if a different button is pressed, or after 2-3 seconds of inactivity.

This allows fullscreen preview mode to not compromise functionality or be a cumbersome hindrance. And I think we can agree that's an all around good thing.

**Comment by WubTheGame** [comment]
Great ideas, i'd love to see this implemented.
