### ISSUE TITLE
Show theme info

### ISSUE THREAD

**Issue by ErmanSayin** [ErmanSayin/Themely#43]

**Comment by jurassicplayer** [comment]
Also show BGM sampling rate as toggle-able option (since not everyone probably cares about seeing the sampling rate). BCSTM header should normally have it from what [3dbrew](https://www.3dbrew.org/wiki/BCSTM#Stream_Info) says.

**Comment by WubTheGame** [comment]
and maybe you could add your own personal notes and info to it.

**Comment by ErmanSayin** [comment]
i don't think this is required for now
