### ISSUE TITLE
Shuffle Themes not working

### ISSUE THREAD

**Issue by DingFandango** [ErmanSayin/Themely#44]
Most of the time when I try to install 10 themes on shuffle and exit, the themes won't install and I am still left on the original default themes. I have tried setting up the defaults to shuffle to try to get themely shuffles to work but it still will not make them work.

**Comment by Xyphoseos** [comment]
Don't work for me too

**Comment by greenDarkness** [comment]
At most I've been able to install up to 5 themes on shuffle with no issues. The 6th theme makes Themely freeze at "Writing to BgmCache_**.bin..."
Thanks you for all your work!

**Comment by KevinBlue18** [comment]
It works for me but BGMs don't loop on the current theme shown.

**Comment by WubTheGame** [comment]
Darkness it was the same for me, but i'm updating my CIA to the latest release now so i might not get the same issue.
