### ISSUE TITLE
Long descriptions don't display right

### ISSUE THREAD

**Issue by CodyMKW** [ErmanSayin/Themely#5]
Long descriptions like the one on this theme https://3dsthem.es/9043 don't display right on Themely
Heres what it looks like:
![screenshot](http://i.imgur.com/ORKaBGG.jpg)

**Comment by CodyMKW** [comment]
I think what you could is if its long like this stop it at a certain part and put see more then maybe assign a button like L to pull up a box covering the entire top screen that shows the full description press L again hide the it again

**Comment by ErmanSayin** [comment]
I'm on it

**Comment by ErmanSayin** [comment]
Fixed in commit 5f2afcd
