### ISSUE TITLE
Crash when closing BGM preview

### ISSUE THREAD

**Issue by Aevroze** [ErmanSayin/Themely#51]
https://3dsthem.es/12249

I can preview this theme's BGM, but when I close the preview with Y it closes Themely completely. Seems to be an issue specific to this theme.

**Comment by EarnestStalker** [comment]
Just my personal input but shouldn't the closing of the theme be used with B?  As far as I know closing via y results in a crash.  I'm personally not sure how your 3ds isn't crashing but considering it's different.....

**Comment by ErmanSayin** [comment]
This is most likely fixed in v1.4.0 with the addition of the BCSTM player.
