### ISSUE TITLE
Don't download the theme

### ISSUE THREAD

**Issue by acelerador25** [ErmanSayin/Themely#54]
#9 
I see that new qr reader, but after that download, Themely say that is not posible to put the theme because have dowload before, a theme that never I put in the 3ds. What's the problem? The problem comes from that version and is still in the new one a few minutes ago

**Comment by ErmanSayin** [comment]
Which theme is causing this problem?

**Comment by acelerador25** [comment]
Any theme I download from the web say that, why?

**Comment by ErmanSayin** [comment]
Is the themes folder named **exactly** "Themes", or "themes"?

**Comment by acelerador25** [comment]
Themes, and that is on the root of the sd

**Comment by acelerador25** [comment]
I see the last commit from themely in the 3ds.them.es web and have the same bug
![red bug](https://cloud.githubusercontent.com/assets/22378686/26426497/6c23696c-409e-11e7-8fd5-bf4bee1abb42.JPG)
 problem

**Comment by Nomelas** [comment]
I'm seeing the same error

**Comment by acelerador25** [comment]
@Nomelas You downloade the last themely from 3dsthem.es? I use the last one and I can Donload the themes to the 3ds

**Comment by icefire82G** [comment]
@acelerador25 tested with de5a2a3, getting the same error after using both c56c2a1 and de5a2a3, no matter which theme's qr code is scanned.

**Comment by acelerador25** [comment]
I don't say that @icefire82G, I say: After dowloaded the de5a2a3 themely version I haven't getting again the red bug

**Comment by acelerador25** [comment]
I used the last version, fa30e8f, and my console can donwload the themes, but have problems in some sounds themes when I try to play in the .cia

**Comment by icefire82G** [comment]
@acelerador25 I know what you said, but _I_ wasn't able to get it to work on either of those versions. However, the latest commit seems to have fixed the problem.

**Comment by acelerador25** [comment]
that problem @icefire82G, but I need more time for the test (in this moment I'm in lunch)

**Comment by ErmanSayin** [comment]
This should be fixed in 65b7dad
