### ISSUE TITLE
Isn't a real issue, but its inconveniant.

### ISSUE THREAD

**Issue by Zelystin** [ErmanSayin/Themely#55]
If you leave ( press start ) in Themely if it the same reaction that if you press power, so, in NTR on New3ds it can disable NTR occasionelly. 

Its possible to patch them ? Or add a fonction to can press Home button like some homebrews like " mini vMac " or " Pksm " or other ? 

Its just an idea 👍 good work for themely, its beautyfull.

**Comment by ErmanSayin** [comment]
no.
