### ISSUE TITLE
Stuck at "Scanning Themes"

### ISSUE THREAD

**Issue by chazmaniandinkle** [ErmanSayin/Themely#56]
When launching Themely from the home screen, it is stuck at "Scanning themes..." and never progresses.

Some relevant information:
- I currently have the latest bleeding-edge build installed (https://github.com/ErmanSayin/Themely/commit/04c26f6)
- This was installed using the .CIA file via FBI.
- I am using a New 3DS XL on firmware 11.4.0-37U.
- My /themes/ directory is currently empty.

This issue does not affect the latest stable build v1.2.1 on my system
(https://github.com/ErmanSayin/Themely/releases/tag/v1.2.1 )

**Comment by ErmanSayin** [comment]
This seems to be happening because the themes directory is empty, and the code doesn't check for that

Will fix soon
