### ISSUE TITLE
Too many themes crash the app

### ISSUE THREAD

**Issue by jakem72360** [ErmanSayin/Themely#6]
I am unable to use Themely on my N3DS XL. I don't know if other users have had any problems but I thought I'd submit as much as I know.

After scanning my themes (for about 60 seconds), the menu is displayed but crashes after about five seconds or so. I have tried disabling both the N3DS's clock and L2 cache in Luma's settings but the app still crashes. I have attached the dump file, the crash information (onscreen) and a list of all themes and their sizes in case the issue is buffering such a large number of themes, zip's or preview images.

[Crash Information.txt](https://github.com/ErmanSayin/Themely/files/957688/Crash.Information.txt)
[Themes.txt](https://github.com/ErmanSayin/Themely/files/957689/Themes.txt)
[crash_dump_00000000.zip](https://github.com/ErmanSayin/Themely/files/957694/crash_dump_00000000.zip)

**Comment by ErmanSayin** [comment]
I'm on it

**Comment by ErmanSayin** [comment]
Fixed in commit ac76b0a2996cec34f6ac4ddbe23cfedaf2e978bd
