### ISSUE TITLE
Error installing theme.

### ISSUE THREAD

**Issue by Zelystin** [ErmanSayin/Themely#60]
Theme : https://3dsthem.es/45
Error : 

" Une erreur est survenue. Vous avez Themely version c56c2a1-git.
Content-Disposition header not in response. "

Screen colour : Red.

Installed : by QR code ( FBI ) since 20 minutes ago ( 18h10 )

**Comment by ErmanSayin** [comment]
This was an issue from the site, it's now fixed.
