### ISSUE TITLE
"Failed To Move From Temporary Path To /Themes" Error For Specific Themes

### ISSUE THREAD

**Issue by Pepy550** [ErmanSayin/Themely#67]
I'm using the 46e000c-git nightly build right now and when I try to download these specific themes (https://3dsthem.es/13329, https://3dsthem.es/13187 and https://3dsthem.es/6283) via QR Code, I get an error for moving to temporary path from /Themes. Downloading all the other themes works fine, I tried reinstalling the build and the same error happens..

**Comment by ErmanSayin** [comment]
Duplicate of #54.
