### ISSUE TITLE
QR Code downloads on certain themes (0xd8a0a03c)

### ISSUE THREAD

**Issue by icefire82G** [ErmanSayin/Themely#73]
Trying to install a theme via qr code (https://3dsthem.es/13561) and it's returning the error code in the title saying "failed to download zip file".

Running stable 1.3

**Comment by BotAletz** [comment]
I have the same problem with qr codes scan!

By the way Themely is awsome!

**Comment by TheCodPunch696** [comment]
I am also having this problem to.

**Comment by ErmanSayin** [comment]
Sorry lads, there was a server misconfiguration on the site

**Comment by BotAletz** [comment]
So it's fixed?

**Comment by TheCodPunch696** [comment]
Yes

**Comment by TheCodPunch696** [comment]
I tested it

**Comment by BotAletz** [comment]
Thanks Erman!!! <3
