### ISSUE TITLE
Scanning CIA QR Codes causes arm11 data abort exception

### ISSUE THREAD

**Issue by icefire82G** [ErmanSayin/Themely#74]
Accidentally scanned a bleeding edge qr code that I had open on stable 1.3.0. Here's a photo of the exception caused: http://imgur.com/a/BASCV

Exception occurs on all versions that I tested (stable 1.1, 1.2, and all bleeding edge builds since 46e000c)

**Comment by icefire82G** [comment]
The one I used specifically was the one for the latest bleeding-edge, but any qr code that links directly to a cia file causes the error.

**Comment by RubberBrony** [comment]
I too get data aborts with those, specifically using the .3dsx builds.
