### ISSUE TITLE
Crash with a red bottom screen

### ISSUE THREAD

**Issue by Zemogiter** [ErmanSayin/Themely#79]
When I am trying to launch Themely it soft-locks with a red bottom screen. Tried both latest stable and latest bleeding edge build.
New 3DS 11.4 OFW, using ninjahax to access homebrew launcher.

**Comment by ErmanSayin** [comment]
Update your payload

**Comment by Zemogiter** [comment]
Just did still crashes

**Comment by AnalogMan151** [comment]
Same here, using FreakyHax as entry point. Payload is all up to date.
