### ISSUE TITLE
add static url that pulls latest themely build on 3dsthem.es

### ISSUE THREAD

**Issue by zweilous** [ErmanSayin/Themely#80]
having something like ".../latest/themely.cia" and ".../latest/themely.3dsx" that can pull the build from the most recent commit makes it easier to update themely through an existing app like multiupdater. kind of like d0k3's hourlies on his site

i'm aware that self-updating is built into the app itself but since there's already a page of all the nightly builds, i was wondering if this could be a small and simple addition just to give a little more flexibility. if it's redundant for this reason then i understand

**Comment by ErmanSayin** [comment]
Github doesn't provide a way to access uploaded files of latest release directly, the app could parse https://api.github.com/repos/ErmanSayin/Themely-bleeding/releases/latest to get the URL to the latest nightly release
