### ISSUE TITLE
Changing license to ARR is a violation of GPLv2

### ISSUE THREAD

**Issue by astronautlevel2** [ErmanSayin/Themely#83]
Freetype in portlibs is downloaded from GNU Savannah, and licensed under GPLv2. Under GPLv2, it is against the rules to license your derivative with a non-GPL compatible license, which ARR is. Therefore, your project is breaking the GPL licensing.

**Comment by astronautlevel2** [comment]
Although commit a68ddff does fix the issue by not providing freetype, the better solution would've been to simply change the freetype url in portlibs. As it is now, your project cannot be compiled without manually getting the dependencies.

**Comment by ErmanSayin** [comment]
ok

**Comment by fox8091** [comment]
That also doesn't fix the issue. You have to amend project history to correctly fix it, as that commit is still in violation. Also, changing to ARR doesn't affect the license of previous commits. You can't retroactively remove someone's rights.
