### ISSUE TITLE
Y button

### ISSUE THREAD

**Issue by EarnestStalker** [ErmanSayin/Themely#85]
It's a rather simple fix but pressing the Y button (during the playback) will cause the 3ds to crash resulting in a dumb file.

This should be a rather simple fix for you.

**Comment by ErmanSayin** [comment]
Does this occur for a specific theme, or all of themes you have? Where'd you get the themes?

**Comment by ErmanSayin** [comment]
This is most likely fixed in v1.4.0 with the addition of the BCSTM player.
