### ISSUE TITLE
Themely not launching

### ISSUE THREAD

**Issue by mr720gamer** [ErmanSayin/Themely#87]
When I launch the latest themely bleeding edge build, it doesn't start. It goes to a black top screen and a red bottom screen. I am on 11.4 ofw using doodlebomb.

**Comment by ErmanSayin** [comment]
Update your homebrew payload

**Comment by AnalogMan151** [comment]
I am also having this issue on 11.5U using FreakyForms Deluxe as the Homebrew entry point. I can load the Homebrew 2.0 menu and when selecting Themely it stalls on a bottom red screen. Does this require CFW and cannot work with just Homebrew alone?

**Comment by mr720gamer** [comment]
Yeah updating my payload didn't work

**Comment by AnalogMan151** [comment]
Wait, so the issue was closed without confirming that the suggestion resolved your issue? Looks like a mistake in issue handling was made. I'm sure it'll be re-opened and investigated or CFW requirements clarified and README updated shortly.

**Comment by mr720gamer** [comment]
It was my fault cause I never stated if it did fix it.
