### ISSUE TITLE
QR code reader for remote theme download

### ISSUE THREAD

**Issue by ErmanSayin** [ErmanSayin/Themely#9]
This could be used until #3 is realized

**Comment by Jan200101** [comment]
Themely then needs to be able to decompress zip files which the QR codes are pointing to

**Comment by ErmanSayin** [comment]
@Jan200101 Themely can already read ZIP files

**Comment by Jan200101** [comment]
well then
bugger me

**Comment by sks316** [comment]
I assume that this means that 3dsthem.es will begin generating QR Codes for themes.

**Comment by ErmanSayin** [comment]
b2e1328
