### ISSUE TITLE
You forgot to credit nlohmann/json

### ISSUE THREAD

**Issue by ahoischen** [ErmanSayin/Themely#94]
The copyright notices in the app are missing https://github.com/nlohmann/json which you are using under the MIT license. I know that you are using this library because of the strings that are included in the binary.

Offtopic: Banksymate is either great at shock humor or absolutely horrible (and wrong).

**Comment by banksymate** [comment]
we do not credit these mr.'s under the mit license because they are under the transgender community lgbt and we do not support those things.

**Comment by ErmanSayin** [comment]
thanks.
