### ISSUE TITLE
Can't exit QR code scanner on latest version

### ISSUE THREAD

**Issue by OctoNezd** [ErmanSayin/Themely#96]

**Comment by ErmanSayin** [comment]
Just hold the B button.

**Comment by OctoNezd** [comment]
Then why there is an exit button on touch screen which doesn't work?🤔

_Sent from my LeEco X527 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ErmanSayin** [comment]
well you can hold that button as well but the b button is easier
